version: '3.8'
services:
  expo-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "19000:19000"  # Metro bundler
      - "19001:19001"  # Expo DevTools
      - "19002:19002"  # Expo CLI
      - "19006:19006"  # Web (optional)
      - "8081:8081"    # Metro alternative
    environment:
      - PLATFORM=${PLATFORM:-expo}
      - SUPABASE_IP=${SUPABASE_IP:-localhost}
      - MQTT_IP=${MQTT_IP:-localhost}
      - HOST_IP=${HOST_IP:-localhost}
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=${HOST_IP:-localhost}
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge