services:
  expo-frontend:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "19000:19000"  
      - "19001:19001"  
      - "19002:19002"
      - "19006:19006"  
      - "8081:8081"    
    environment:
      - PLATFORM=${PLATFORM:-expo}
      - HOST_IP=${HOST_IP:-localhost}
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=${HOST_IP:-localhost}
    volumes:
      - .:/app
      - /app/node_modules 
      - /app/.expo
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - frontend-network
      - supabase_default
      - app-network

networks:
  frontend-network:
    external: true
  supabase_default:
    external: true
  app-network:
    external: true