version: '3.8'
services:
  face-verification-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: face-verification-api
    ports:
      - "9002:9002"
    restart: unless-stopped
    stdin_open: true
    tty: true
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      - ./config:/app/config:rw