name: Face-Verification-API-Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pillow
        # Install bc for floating point calculations
        sudo apt-get update
        sudo apt-get install -y bc
    
    - name: Check if API service is configured
      run: |
        if [ -f "./extensions/docker-compose.test.yml" ] || [ -f "./extensions/compose.yml" ]; then
          echo "Docker compose file found in extensions directory"
          ls -la ./extensions/*compose*.yml 2>/dev/null || echo "No compose files found"
        else
          echo "No docker compose file found in extensions - will test against localhost"
        fi
    
    - name: Start Face Verification API (if docker-compose exists)
      run: |
        if [ -f "./extensions/docker-compose.test.yml" ]; then
          echo "Starting face-verification-api service with docker-compose..."
          cd ./extensions
          docker compose --file docker-compose.test.yml up -d face-verification-api --wait
        elif [ -f "./extensions/compose.yml" ]; then
          echo "Starting face-verification-api service with compose.yml..."
          cd ./extensions
          docker compose --file compose.yml up -d face-verification-api --wait
        else
          echo "No compose file found - assuming API runs separately"
        fi
    
    - name: Wait for API to be ready
      run: |
        echo 'Waiting for Face Verification API to start...'
        API_URL="http://localhost:9002"
        
        # Wait up to 60 seconds for API to respond
        for i in {1..30}; do
          if curl -s --max-time 5 "$API_URL/health" >/dev/null 2>&1; then
            echo 'API is ready!'
            exit 0
          fi
          echo "Waiting for API... attempt $i/30"
          sleep 2
        done
        
        echo 'API failed to start within 60 seconds'
        if command -v docker >/dev/null 2>&1; then
          echo 'Docker container logs:'
          docker ps -a
          for container in $(docker ps -aq 2>/dev/null); do
            echo "--- Logs for container $container ---"
            docker logs "$container" 2>/dev/null || echo 'No logs available'
          done
        fi
        exit 1
    
- name: Test Health Endpoint
  run: |
    echo "=== Testing Health Endpoint ==="
    API_URL="http://localhost:9002"

    if ! response=$(curl -s -w "%{http_code}" -o health_response.json "$API_URL/health" 2>/dev/null); then
      response="000"
    fi

    if [ "$response" = "200" ]; then
      echo "✅ Health check PASSED"
      echo "Response:"
      if [ -f health_response.json ] && [ -s health_response.json ]; then
        python3 -m json.tool < health_response.json || cat health_response.json
      fi

      python3 -c "import json
import sys
try:
    with open('health_response.json') as f:
        content = f.read().strip()
        if not content:
            print('❌ Empty response')
            sys.exit(1)
        data = json.loads(content)
    required = ['status', 'model_loaded', 'model_type', 'device']
    missing = [field for field in required if field not in data]
    if missing:
        print(f'❌ Missing fields: {missing}')
        sys.exit(1)
    if data.get('status') != 'healthy':
        print(f'❌ Status not healthy: {data.get(\"status\")}')
        sys.exit(1)
    print('✅ All required fields present and status is healthy')
except Exception as e:
    print(f'❌ Error parsing response: {e}')
    sys.exit(1)"
    else
      echo "❌ Health check FAILED with status code: $response"
      [ -f health_response.json ] && cat health_response.json || echo "No response body"
      exit 1
    fi
    
    - name: Test Model Info Endpoint
      run: |
        echo "=== Testing Model Info Endpoint ==="
        API_URL="http://localhost:9002"
        
        if ! response=$(curl -s -w "%{http_code}" -o model_info_response.json "$API_URL/model_info" 2>/dev/null); then
          response="000"
        fi
        
        if [ "$response" = "200" ]; then
          echo "✅ Model info check PASSED"
          echo "Response:"
          if [ -f model_info_response.json ] && [ -s model_info_response.json ]; then
            python3 -m json.tool < model_info_response.json || cat model_info_response.json
          fi
          
          # Check required fields
          python3 -c "
          import json
          import sys
          try:
              with open('model_info_response.json') as f:
                  content = f.read().strip()
                  if not content:
                      print('❌ Empty response')
                      sys.exit(1)
                  data = json.loads(content)
              required = ['model_loaded', 'model_type', 'total_parameters', 'embedding_size']
              missing = [field for field in required if field not in data]
              if missing:
                  print(f'❌ Missing fields: {missing}')
                  sys.exit(1)
              print('✅ All required fields present')
              print(f'Model type: {data.get(\"model_type\")}')
              print(f'Parameters: {data.get(\"total_parameters\")}')
          except Exception as e:
              print(f'❌ Error parsing response: {e}')
              sys.exit(1)
          "
        elif [ "$response" = "503" ]; then
          echo "⚠️ Model not loaded (503) - this may be expected"
          [ -f model_info_response.json ] && cat model_info_response.json || echo "No response body"
        else
          echo "❌ Model info check FAILED with status code: $response"
          [ -f model_info_response.json ] && cat model_info_response.json || echo "No response body"
          exit 1
        fi

    - name: Create Test Images
      run: |
        echo "=== Creating Test Images ==="
        python3 -c "
        from PIL import Image
        import base64
        import io
        import json

        def create_test_image(size=(160, 160), color=(255, 0, 0)):
            img = Image.new('RGB', size, color)
            buffer = io.BytesIO()
            img.save(buffer, format='PNG')
            img_str = base64.b64encode(buffer.getvalue()).decode()
            return f'data:image/png;base64,{img_str}'

        # Create test images
        red_image = create_test_image((160, 160), (255, 0, 0))
        green_image = create_test_image((160, 160), (0, 255, 0))
        blue_image = create_test_image((160, 160), (0, 0, 255))

        # Save for later use
        test_data = {
            'red_image': red_image,
            'green_image': green_image,
            'blue_image': blue_image
        }

        with open('test_images.json', 'w') as f:
            json.dump(test_data, f)
        
        print('✅ Test images created successfully')
        "
            
    - name: Test Compare Endpoint
      run: |
        echo "=== Testing Compare Endpoint ==="
        API_URL="http://localhost:9002"
        
        # Create payload for comparison
        python3 -c "
        import json
        with open('test_images.json') as f:
            images = json.load(f)
        
        payload = {
            'image1': images['red_image'],
            'image2': images['green_image'],
            'threshold': 0.6
        }
        
        with open('compare_payload.json', 'w') as f:
            json.dump(payload, f)
        "
        
        if ! response=$(curl -s -w "%{http_code}" -X POST \
          -H "Content-Type: application/json" \
          -d @compare_payload.json \
          -o compare_response.json \
          "$API_URL/compare" 2>/dev/null); then
          response="000"
        fi
        
        if [ "$response" = "200" ]; then
          echo "✅ Compare endpoint PASSED"
          echo "Response:"
          if [ -f compare_response.json ] && [ -s compare_response.json ]; then
            python3 -m json.tool < compare_response.json || cat compare_response.json
          fi
          
          # Validate response structure
          python3 -c "
          import json
          import sys
          try:
              with open('compare_response.json') as f:
                  content = f.read().strip()
                  if not content:
                      print('❌ Empty response')
                      sys.exit(1)
                  data = json.loads(content)
              required = ['match', 'similarity_score', 'confidence', 'model_type']
              missing = [field for field in required if field not in data]
              if missing:
                  print(f'❌ Missing fields: {missing}')
                  sys.exit(1)
              print('✅ All required fields present')
              print(f'Match: {data.get(\"match\")}')
              print(f'Similarity Score: {data.get(\"similarity_score\")}')
          except Exception as e:
              print(f'❌ Error parsing response: {e}')
              sys.exit(1)
          "
        elif [ "$response" = "503" ]; then
          echo "⚠️ Service unavailable (503) - model may not be loaded"
          [ -f compare_response.json ] && cat compare_response.json || echo "No response body"
        else
          echo "❌ Compare endpoint FAILED with status code: $response"
          [ -f compare_response.json ] && cat compare_response.json || echo "No response body"
          exit 1
        fi
    
    - name: Test Compare Invalid Data
      run: |
        echo "=== Testing Compare Endpoint with Invalid Data ==="
        API_URL="http://localhost:9002"
        
        # Test with missing image1
        echo '{"image2": "data:image/png;base64,invalid"}' > invalid_payload.json
        
        if ! response=$(curl -s -w "%{http_code}" -X POST \
          -H "Content-Type: application/json" \
          -d @invalid_payload.json \
          -o invalid_response.json \
          "$API_URL/compare" 2>/dev/null); then
          response="000"
        fi
        
        if [ "$response" = "400" ]; then
          echo "✅ Invalid data test PASSED - correctly rejected with 400"
        else
          echo "❌ Invalid data test FAILED - expected 400, got: $response"
          [ -f invalid_response.json ] && cat invalid_response.json || echo "No response body"
        fi
    
    - name: Test Batch Compare Endpoint
      run: |
        echo "=== Testing Batch Compare Endpoint ==="
        API_URL="http://localhost:9002"
        
        # Create batch payload
        python3 -c "
        import json
        with open('test_images.json') as f:
            images = json.load(f)
        
        payload = {
            'pairs': [
                {'image1': images['red_image'], 'image2': images['green_image']},
                {'image1': images['green_image'], 'image2': images['blue_image']},
                {'image1': images['red_image'], 'image2': images['blue_image']}
            ],
            'threshold': 0.6
        }
        
        with open('batch_payload.json', 'w') as f:
            json.dump(payload, f)
        "
        
        if ! response=$(curl -s -w "%{http_code}" -X POST \
          -H "Content-Type: application/json" \
          -d @batch_payload.json \
          -o batch_response.json \
          "$API_URL/batch_compare" 2>/dev/null); then
          response="000"
        fi
        
        if [ "$response" = "200" ]; then
          echo "✅ Batch compare endpoint PASSED"
          echo "Response:"
          if [ -f batch_response.json ] && [ -s batch_response.json ]; then
            python3 -m json.tool < batch_response.json || cat batch_response.json
          fi
          
          # Validate response structure
          python3 -c "
          import json
          import sys
          try:
              with open('batch_response.json') as f:
                  content = f.read().strip()
                  if not content:
                      print('❌ Empty response')
                      sys.exit(1)
                  data = json.loads(content)
              required = ['matches', 'detailed_results', 'total_pairs', 'successful_pairs']
              missing = [field for field in required if field not in data]
              if missing:
                  print(f'❌ Missing fields: {missing}')
                  sys.exit(1)
              if len(data.get('matches', [])) != 3:
                  print(f'❌ Expected 3 matches, got: {len(data.get(\"matches\", []))}')
                  sys.exit(1)
              print('✅ Batch compare validation passed')
              print(f'Total pairs: {data.get(\"total_pairs\")}')
              print(f'Successful pairs: {data.get(\"successful_pairs\")}')
          except Exception as e:
              print(f'❌ Error parsing response: {e}')
              sys.exit(1)
          "
        elif [ "$response" = "503" ]; then
          echo "⚠️ Service unavailable (503) - model may not be loaded"
          [ -f batch_response.json ] && cat batch_response.json || echo "No response body"
        else
          echo "❌ Batch compare endpoint FAILED with status code: $response"
          [ -f batch_response.json ] && cat batch_response.json || echo "No response body"
        fi
    
    - name: Test Verify User Endpoint
      run: |
        echo "=== Testing Verify User Endpoint ==="
        API_URL="http://localhost:9002"
        
        # Create user verification payload
        python3 -c "
        import json
        with open('test_images.json') as f:
            images = json.load(f)
        
        payload = {
            'userId': 'test_user_123',
            'images': [images['red_image']],
            'threshold': 0.6,
            'min_verification_images': 1,
            'max_verification_images': 5
        }
        
        with open('verify_payload.json', 'w') as f:
            json.dump(payload, f)
        "

        if ! response=$(curl -s -w "%{http_code}" -X POST \
          -H "Content-Type: application/json" \
          -d @verify_payload.json \
          -o verify_response.json \
          "$API_URL/verify_user" 2>/dev/null); then
          response="000"
        fi
        
        if [ "$response" = "200" ]; then
          echo "✅ Verify user endpoint PASSED"
          if [ -f verify_response.json ] && [ -s verify_response.json ]; then
            python3 -m json.tool < verify_response.json || cat verify_response.json
          fi
        elif [ "$response" = "404" ]; then
          echo "✅ Expected failure - no verification images found (404)"
          [ -f verify_response.json ] && cat verify_response.json || echo "No response body"
        elif [ "$response" = "503" ]; then
          echo "⚠️ Service unavailable (503) - model may not be loaded"
          [ -f verify_response.json ] && cat verify_response.json || echo "No response body"
        else
          echo "❌ Verify user endpoint unexpected status: $response"
          [ -f verify_response.json ] && cat verify_response.json || echo "No response body"
        fi

    - name: Test Performance
      run: |
        echo "=== Testing API Performance ==="
        API_URL="http://localhost:9002"
        
        # Test health endpoint performance
        echo "Testing health endpoint response time..."
        start_time=$(date +%s.%N)
        curl -s --max-time 10 "$API_URL/health" > /dev/null 2>&1 || true
        end_time=$(date +%s.%N)
        health_time=$(echo "$end_time - $start_time" | bc -l 2>/dev/null || echo "0")
        
        if [ -n "$health_time" ] && (( $(echo "$health_time < 2.0" | bc -l 2>/dev/null) )); then
          echo "✅ Health endpoint performance PASSED: ${health_time}s"
        else
          echo "⚠️ Health endpoint response time: ${health_time}s"
        fi
        
        # Test compare endpoint performance
        echo "Testing compare endpoint response time..."
        if [ -f compare_payload.json ]; then
          start_time=$(date +%s.%N)
          curl -s --max-time 15 -X POST \
            -H "Content-Type: application/json" \
            -d @compare_payload.json \
            "$API_URL/compare" > /dev/null 2>&1 || true
          end_time=$(date +%s.%N)
          compare_time=$(echo "$end_time - $start_time" | bc -l 2>/dev/null || echo "0")
          
          if [ -n "$compare_time" ] && (( $(echo "$compare_time < 10.0" | bc -l 2>/dev/null) )); then
            echo "✅ Compare endpoint performance PASSED: ${compare_time}s"
          else
            echo "⚠️ Compare endpoint response time: ${compare_time}s"
          fi
        else
          echo "⚠️ Compare payload not found, skipping performance test"
        fi

    - name: Show API logs (if containerized)
      if: always()
      run: |
        echo "=== API Container Logs ==="
        if command -v docker >/dev/null 2>&1; then
          echo "Docker containers:"
          docker ps -a 2>/dev/null || echo "No containers found"
          echo ""
          echo "Container logs:"
          for container in $(docker ps -aq 2>/dev/null); do
            echo "--- Logs for container $container ---"
            docker logs "$container" 2>&1 || echo "No logs available"
            echo ""
          done
        else
          echo "Docker not available - skipping container logs"
        fi

    - name: Cleanup
      if: always()
      run: |
        echo "=== Cleanup ==="
        if [ -f "./extensions/docker-compose.yml" ] || [ -f "./extensions/compose.yml" ]; then
          echo "Stopping services..."
          cd ./extensions
          docker compose down 2>/dev/null || true
        fi
        
        # Clean up test files
        rm -f health_response.json model_info_response.json
        rm -f compare_response.json batch_response.json verify_response.json
        rm -f compare_payload.json batch_payload.json verify_payload.json
        rm -f invalid_payload.json invalid_response.json
        rm -f test_images.json
        
        echo "✅ Cleanup completed"